plugins {
    id("java")
    id 'org.springframework.boot' version '3.2.5'

    id 'io.spring.dependency-management'version'1.1.4'
}

group = "org.example"
version = "1.0-SNAPSHOT"
sourceCompatibility ='21'


repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.mysql:mysql-connector-j:8.3.0'
    implementation 'org.xerial:sqlite-jdbc:3.45.1.0'
    implementation 'com.github.haifengl:smile-core:2.6.0'
    implementation 'com.github.haifengl:smile-core:3.0.1'
    implementation 'mysql:mysql-connector-java:8.0.33'
    implementation 'com.sparkjava:spark-core:2.9.4'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.sparkjava:spark-core:2.9.4'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'mysql:mysql-connector-java:8.0.33'
    implementation 'com.sparkjava:spark-core:2.9.4'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'mysql:mysql-connector-java:8.0.33'

    // Jetty modules (required for Spark)
    implementation 'org.eclipse.jetty:jetty-server:9.4.51.v20230217'
    implementation 'org.eclipse.jetty:jetty-servlet:9.4.51.v20230217'
    implementation 'org.eclipse.jetty:jetty-util:9.4.51.v20230217'
    implementation 'org.eclipse.jetty:jetty-http:9.4.51.v20230217'
    implementation 'org.eclipse.jetty:jetty-io:9.4.51.v20230217'
    implementation 'org.eclipse.jetty:jetty-server:9.4.51.v20230217'
    implementation 'org.eclipse.jetty:jetty-servlet:9.4.51.v20230217'

}



tasks.test {
    useJUnitPlatform()
}